import "../view/styles/home.css"
import "../view/styles/fonts.css"
import { Inter } from 'next/font/google'
import { InputHookForm } from "../view/components/InputHookForm";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div className="container">
      <InputHookForm label="Novo cliente"></InputHookForm>
    </div>
  )
}
